### ISSUE TITLE
virus found (by AVG)

### ISSUE THREAD

**Issue by cisko99za** [sandboxie/sandboxie#32]
on latest 5.41.2 version my AVG antivirus found virus on file SbieDrv.sys infected by Win64:DangerousSig [Tri]....
with previous version 5.33 no problem....

**Comment by OldHolborn01** [comment]
Read this ...

[https://github.com/sandboxie-plus/Sandboxie/issues/52]

**Comment by cisko99za** [comment]
tanxs. and i know, false alarm.
but i hope on next release, this issue will be resolved!

**Comment by DavidXanatos** [comment]
> 
> 
> tanxs. and i know, false alarm.
> but i hope on next release, this issue will be resolved!

Probably not, given the rate I get donations it will take a year at least.

**Comment by n01337** [comment]
@DavidXanatos: Consider instructing users to put Windows into "Test mode" instead, so that it accepts self-signed drivers. This works very well for e.g. the Sony Xperia rooting tool "flashtool" - and there would be no virus warnings anymore. This might be the more "approachable" option instead of highly suspicious certificates.
